name: ssatravels_app
description: SSA Tours & Travels Mobile Application
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  provider: ^6.1.1
  crypto: ^3.0.3
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  url_launcher: ^6.3.2 
  fluttertoast: ^9.0.0 
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.2.3
  qr_flutter: ^4.1.0

  google_maps_flutter: ^2.14.0
  dropdown_button2: ^2.3.0  
  flutter_map: ^5.0.0
  flutter_google_maps_webservices: ^1.1.1
  #flutter_polyline_points: ^3.1.0  
  
  
  permission_handler: ^11.0.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  geocoding: ^2.1.3
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  syncfusion_flutter_pdf: ^32.1.23
  open_file: ^3.5.11
  path_provider: ^2.1.5 
  firebase_messaging: ^16.1.1
  shared_preferences: ^2.5.4
  location: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1  

flutter:
  uses-material-design: true

  assets:
    - assets/icon/ssa-icon.png
    - assets/ssa-logo.png
    - assets/ssa-travels.png
    - assets/data/distances.json
    - assets/data/tolls.json
    - assets/data/city_coordinates.json
    - assets/data/city_suggestions.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ssa-icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ssa-logo.png"